include: package:leancode_lint/analysis_options.yaml

# Optional lint rules configuration
custom_lint:
  rules:

analyzer:
  plugins:
    # Required for our custom lints support
    - custom_lint
  exclude:
    - '**/*.g.dart'

