// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKMRcFOUCiiLtpLuTi6CIXLxhwclqwQo',
    appId: '1:176363757747:web:bd0b4cd29aa578d9b950c6',
    messagingSenderId: '176363757747',
    projectId: 'memodeck-a7965',
    authDomain: 'memodeck-a7965.firebaseapp.com',
    storageBucket: 'memodeck-a7965.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6naSjkBe38JQYI_oOeT0lu9SvxUqc1NY',
    appId: '1:176363757747:android:8d3a57121cc4c977b950c6',
    messagingSenderId: '176363757747',
    projectId: 'memodeck-a7965',
    storageBucket: 'memodeck-a7965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuFuKtaAP1k48Rph7UxeiAcWWjxLgjBs',
    appId: '1:176363757747:ios:d3b2dce997ed0631b950c6',
    messagingSenderId: '176363757747',
    projectId: 'memodeck-a7965',
    storageBucket: 'memodeck-a7965.firebasestorage.app',
    iosBundleId: 'com.example.memoDeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuFuKtaAP1k48Rph7UxeiAcWWjxLgjBs',
    appId: '1:176363757747:ios:d3b2dce997ed0631b950c6',
    messagingSenderId: '176363757747',
    projectId: 'memodeck-a7965',
    storageBucket: 'memodeck-a7965.firebasestorage.app',
    iosBundleId: 'com.example.memoDeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKMRcFOUCiiLtpLuTi6CIXLxhwclqwQo',
    appId: '1:176363757747:web:0410d5c0bedf0140b950c6',
    messagingSenderId: '176363757747',
    projectId: 'memodeck-a7965',
    authDomain: 'memodeck-a7965.firebaseapp.com',
    storageBucket: 'memodeck-a7965.firebasestorage.app',
  );
}
